# Generated by Django 4.0.10 on 2023-08-15 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='urlfotoasistencia',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='hora_registro',
            field=models.DateTimeField(),
        ),
    ]
